# Your Website Title
title: boluonai

# Your Website URL
url: 'http://boluonai.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: bolengni
tagline: Software Developer, IoT, Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: å­™æ–‡å©·æ˜¯å¤´ğŸ–ï¼ï¼ï¼
description_tiny: å“ˆå“ˆå“ˆï¼Œç¬‘æ­»
email: 2920268098@qq.com
website: boluonai.github.io # do not add http://
linkedin: realmelvinchng
github: melvinchng
twitter: '@JsMA0Az5KyD32Of'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm